*** Variables ***
${accept_cookies_btn}                //button[@id='onetrust-accept-btn-handler']
${get_capco_text}                    /html/body/div/div/div[3]/div[2]/div/a
${play_video_btn}                    //img[@src='/Content/images/icon-youtube.svg']
${search_for_opportunity_btn}        //a[@class='btn-big']
${find_your_job_text}                //h1[@class='c-hero-banner__title']
${number_of_job_found_txt}           //h2/span